import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link"


export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos")
  const data = await res.json()

  return {
    props: {
      todose: data
    }
  }
}

export default function Home({ todose }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/About">about</Link>



      {todose?.length == 0 ? (<div>loading...</div>) : (todose.map((todo) => {
        return (
          <div key={todo.id}>
            <p>
              {todo.id}: {todo.title}
            </p>
          </div>
        )
      }))

      }

    </div>
  )
}
